version: '3.3'

# networks:
#   vpcbr:
#       driver: bridge
#       ipam:
#         config:
#           - subnet: 10.5.0.0/16

services:
  db:
    image: mysql:5.7
    container_name: colmex.mysql
    env_file:
      - ./.env
    restart: always
    # volumes:
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
    #   - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    # networks:
    #   vpcbr:
    #     ipv4_address: 10.5.0.7
    expose:
      - ${MYSQL_PORT}

  solr:
    #image: solr:7.0.1
    container_name: ${SOLR_NAME}
    restart: always
    build: ./solr
    ports:
      - "${SOLR_PORT}:${SOLR_DOCKER_PORT}"
    #command: sudo chmod -R 777 /opt/solr/server/solr/mycores/hydra-development/
    volumes:
      #- solr:/opt/solr/server/solr/mycores
      #- ./config/:/opt/solr/server/solr/
      - ./${SOLR_VOLUME_LOCAL}:/opt/solr/server/solr/mycores/${SOLR_CORE}/conf
    #entrypoint: sudo chmod -R 777 /opt/solr/server/solr/mycores/hydra-development/
    # networks:
    #   vpcbr:
    #     ipv4_address: 10.5.0.8
    #entrypoint:
      #- docker-entrypoint.sh

  fcrepo:
    #image: ualbertalib/docker-fcrepo4
    image: samvera/fcrepo4:4.7.3
    container_name: ${FEDORA_NAME}
    #build: ./fcrepo
    ports:
      - ${FEDORA_LOCAL_PORT}:${FEDORA_DOCKER_PORT}
    expose:
      - ${FEDORA_LOCAL_PORT}
    # networks:
    #   vpcbr:
    #     ipv4_address: 10.5.0.6
    depends_on:
      - db
  
  redis:
    image: redis
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    restart: always
    expose:
      - ${REDIS_DOCKER_PORT}

  app:
    build: ./colmex_hyrax
    container_name: ${WEB_NAME}
    volumes:
      - ./${WEB_CONTAINER}:/${WEB_WORK_DIR}
      - ./${FITS_LOCAL_FILE}:/${FITS_WORK_DIR}
    working_dir: /${WEB_WORK_DIR}
    # command:
    #   - puma
    ports:
      - ${WEB_LOCAL_PORT}:${WEB_DOCKER_PORT}
    command: bash -c "/bin/docker-entrypoint.sh"
    # networks:
    #   vpcbr:
    #     ipv4_address: 10.5.0.5
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
  
  web:
    container_name: colmex.nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on: 
      - app
    volumes:
      - ./colmex_hyrax/public/:/colmex_hyrax/public/
    ports:
      - 80:80